#+OPTIONS: <:nil d:nil timestamp:t ^:nil tags:nil toc:nil num:nil \n:t
#+STARTUP: fninline inlineimages showall

* SDL - Rebase a branch onto another branch - Example 2
In order to combine the content from the gluten-free and the vegan
branches in this example we will rebase ~gluten-free~ onto ~vegan~.
The [[file:sdl_rebase_01.org::*SDL - Rebase a branch onto another branch - Example 1][first example SDL]] a similar result but by rebasing the other way
around.

Just like we rebased our changes of ~vegan~ onto ~gluten_free~, we can do it the
other way around:

#+begin_src shell-script
# Create two new branches to start all over again with the rebase
git branch vegan_2 e40def1
git branch gluten_free_2 716409e
git graph -n 14
#+end_src
#+begin_example
 * c85a553 - (7 minutes ago) add link to table, add notes to recipe
 |           (tag: v_0.2_second_vegan_gf_version, vegan_1)
 * 93a0b93 - (9 minutes ago) add replacement for honey
 * 28e0a1a - (9 minutes ago) add table of replacements in vegan recipes
 | *   3525589 - (11 months ago) merge gluten-free and vegan recipes
 | |             (tag: v_0.2_first_vegan_gf_version)
 | |\
 | |/
 |/|
 * |   716409e - (11 months ago) Merge branch 'fix_typo' into gluten_free
 | |             (HEAD -> gluten_free_2, gluten_free_1)
 |\ \
 | * | 4a5c4eb - (11 months ago) fix typo in README.md
 * | | 461de20 - (11 months ago) reformat cinemon recipe
 |/ /
 * | 34f83d7 - (11 months ago) update README for gluten-free recipes
 | |           (gluten_free)
 * | 01bb2d4 - (11 months ago) make biscuits recipe gluten free
 | * e40def1 - (11 months ago) add link to table, add notes to recipe (vegan_2)
 | * ec39d14 - (11 months ago) add replacement for honey
 | |           (vegan)
 | * 49e8505 - (11 months ago) add table of replacements in vegan recipes
 | |           (tag: v_0.1_vegan_replacement)
 |/
 | * 5755eba - (11 months ago) replace margarine with butter in biscuit recipe
 | |           (main)
 |/
 * 7d4a511 - (11 months ago) add link in cinemon star recipe
#+end_example
In particular note the above ~HEAD -> gluten_free_2~ which indicates the branch we
have checked out.

This time we check out the ~gluten_free~ branch and we rebase it onto ~vegan~:
#+begin_src shell-script
git checkout gluten_free_2
git rebase vegan_2
#+end_src
#+begin_example
Switched to branch 'gluten_free_2'
usuki% git rebase vegan_2
Auto-merging biscuits.txt
CONFLICT (content): Merge conflict in biscuits.txt
error: could not apply 01bb2d4... make biscuits recipe gluten free
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 01bb2d4... make biscuits recipe gluten free
#+end_example

Like before, we get a conflict. Examining the situation further
#+begin_src shell-script
git status
#+end_src
#+begin_example
interactive rebase in progress; onto e40def1
Last command done (1 command done):
   pick 01bb2d4 make biscuits recipe gluten free
Next commands to do (3 remaining commands):
   pick 34f83d7 update README for gluten-free recipes
   pick 461de20 reformat cinemon recipe
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'gluten_free_2' on 'e40def1'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
        both modified:   biscuits.txt

no changes added to commit (use "git add" and/or "git commit -a")
#+end_example

Weirdly enough, only the /biscuits.txt/ file seems to be affected. Looking at ~git log --graph~ shows:
#+begin_src shell-script
git graph -n 11
#+end_src
#+begin_example
 * c85a553 - (13 minutes ago) add link to table, add notes to recipe
 |           (tag: v_0.2_second_vegan_gf_version, vegan_1)
 * 93a0b93 - (15 minutes ago) add replacement for honey
 * 28e0a1a - (15 minutes ago) add table of replacements in vegan recipes
 | *   3525589 - (11 months ago) merge gluten-free and vegan recipes
 | |             (tag: v_0.2_first_vegan_gf_version)
 | |\
 | |/
 |/|
 * |   716409e - (11 months ago) Merge branch 'fix_typo' into gluten_free
 | |             (gluten_free_2, gluten_free_1)
 |\ \
 | * | 4a5c4eb - (11 months ago) fix typo in README.md
 * | | 461de20 - (11 months ago) reformat cinemon recipe
 |/ /
 * | 34f83d7 - (11 months ago) update README for gluten-free recipes
 * | 01bb2d4 - (11 months ago) make biscuits recipe gluten free
 | * e40def1 - (11 months ago) add link to table, add notes to recipe (HEAD, vegan_2)
 | * ec39d14 - (11 months ago) add replacement for honey (vegan)
#+end_example
Note that ~HEAD~ is now somewhere else - and compare it with the above message from ~git rebase~: It says
#+begin_example
Last command done (1 command done):
   pick 01bb2d4 make biscuits recipe gluten free
#+end_example
Can you spot this number, ~01bb2d4~ in the output? It is the one next to where ~HEAD~ now is.

So as we are rebasing /onto/ ~vegan~, we are already stuck in the first commit (~01bb2d4~) leading towards ~gluten_free~!
